### PR TITLE
Adding clarification to GitHub connection

### PR DESCRIPTION
**Pull request by cssinate**
I feel like this step in their guide is the easiest to overlook. Highlighting it here would have helped me!

### CODE REVIEW

**Comment by budak7273** [comment]
I am all for increasing the clarity of the docs, but they already mention checking for the email in the exact same sentence you edited.

> If you see a "404 This is not the web page you are looking for" error, then you didn't finish linking your account. _**Check for emails from both Epic and GitHub**_, and be sure that you followed the above steps. The page is _not_ dead, this is what GitHub displays as a security measure when someone tries to access a private repo.

Perhaps the sentence as a whole could be reworded to make this more clear?

I went ahead and bolded the notice for checking for an email in the regular docs text for good measure.

**Review by budak7273 — CHANGES_REQUESTED** [review]
See previous comment for requested changes

**Comment by budak7273** [comment]
Also, please change the PR to target the `Dev` branch instead of `master`.

**Comment by veleek** [comment]
I didn't see this PR and I opened up #70 which includes some additional clarifications about get GitHub connection and a few links for verifying it that I think supersedes this commit.

**Comment by Feyko** [comment]
Another PR addressed this issue

**Pull request closed without merging**
