### PR TITLE
Update index.adoc

### PR DESCRIPTION
**Pull request by deantendo**
Grammar and wording changes.

### CODE REVIEW

**Comment by Panakotta00** [comment]
Is there a specific reason why you removed so many "new line" characters?
They organized the articles way better.
If there is no particular reason it would be good if you could add them back ^^

**Comment by deantendo** [comment]
There's sort-of a reason or two:

1. This is my first time using github, so i may have just made a mistake
2. Less line-breaks in text allow it to scale (?) over the available space instead of being artificially forced into a corner.

(Forgive the lack of terminology. Used to be a graphic designer, never a coder, nor web-dev).

**Comment by Vilsol** [comment]
The styling of the text (regarding newlines) in source files is not representative of how it looks in the rendered HTML page. That requires styling changes to the design of the site.

**Comment by deantendo** [comment]
> 
> 
> The styling of the text (regarding newlines) in source files is not representative of how it looks in the rendered HTML page. That requires styling changes to the design of the site.

Fixed, i think....

**Pull request merged**
